version: "3.9"
services:
  routersatellite:
    container_name: router-satellite
    image: knvelasquez/routersatellite:v1.1
    environment:
      # Sets default value 8082 if SPRING_BOOT_PORT is not defined
      - SPRING_BOOT_PORT=${SPRING_BOOT_PORT:-8083}
    ports:
      # Map default value 8082 if SPRING_BOOT_PORT is not defined
      - ${SPRING_BOOT_PORT:-8083}:${SPRING_BOOT_PORT:-8083}
    networks:
      - router-satellite-network
    build:
      context: ./
      dockerfile: Dockerfile

networks:
  router-satellite-network:
    driver: bridge

#set custom port
#SPRING_BOOT_PORT=8181 docker-compose build
#SPRING_BOOT_PORT=8181 docker-compose push
#SPRING_BOOT_PORT=8181 docker-compose up

